"""Code Deployer — 検証済みコードをファイルに書き出し、gitでコミット・プッシュする.

フロー:
    CodeGenerationResult + ValidationResult
    → ファイル書き出し
    → git add + commit
    → git push (オプション)

安全策:
    - ValidationResult.passed == True でなければデプロイしない
    - コミットメッセージにAI生成であることを明記
    - 専用ブランチへのpush
"""

import json
import logging
import subprocess
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional

from system_e.code_generator import CodeGenerationResult
from system_e.code_validator import ValidationResult

logger = logging.getLogger(__name__)

JST = timezone(timedelta(hours=9))
DEPLOY_LOG_DIR = Path(__file__).parent / "data" / "deployments"


class DeploymentResult:
    """デプロイメントの結果."""

    def __init__(
        self,
        success: bool,
        file_path: Optional[Path] = None,
        commit_hash: Optional[str] = None,
        error: Optional[str] = None,
    ):
        self.success = success
        self.file_path = file_path
        self.commit_hash = commit_hash
        self.error = error
        self.deployed_at = datetime.now(JST).isoformat()

    def to_dict(self) -> dict:
        return {
            "success": self.success,
            "file_path": str(self.file_path) if self.file_path else None,
            "commit_hash": self.commit_hash,
            "error": self.error,
            "deployed_at": self.deployed_at,
        }


class CodeDeployer:
    """検証済みコードをデプロイするエンジン.

    Args:
        project_root: gitリポジトリのルート。
        branch: コミット先ブランチ名。None の場合、現在のブランチを使用。
        auto_push: True の場合、コミット後にpushも実行。
    """

    def __init__(
        self,
        project_root: Optional[Path] = None,
        branch: Optional[str] = None,
        auto_push: bool = False,
    ):
        self.project_root = project_root or Path(__file__).parent.parent
        self.branch = branch
        self.auto_push = auto_push
        DEPLOY_LOG_DIR.mkdir(parents=True, exist_ok=True)

    def deploy(
        self,
        gen_result: CodeGenerationResult,
        val_result: ValidationResult,
    ) -> DeploymentResult:
        """検証済みコードをデプロイする.

        Args:
            gen_result: コード生成結果。
            val_result: バリデーション結果。passed=True 必須。

        Returns:
            DeploymentResult: デプロイの結果。
        """
        if not val_result.passed:
            error_msg = (
                f"Validation failed: "
                f"{sum(1 for i in val_result.issues if i.severity == 'error')} errors"
            )
            logger.error("[Deployer] %s", error_msg)
            return DeploymentResult(success=False, error=error_msg)

        try:
            # 1. ファイル書き出し
            file_path = self._write_file(gen_result)

            # 2. git commit
            commit_hash = self._git_commit(file_path, gen_result)

            # 3. git push (オプション)
            if self.auto_push:
                self._git_push()

            # 4. デプロイログ保存
            result = DeploymentResult(
                success=True,
                file_path=file_path,
                commit_hash=commit_hash,
            )
            self._save_deploy_log(gen_result, val_result, result)

            logger.info(
                "[Deployer] Successfully deployed: %s → %s (commit: %s)",
                gen_result.module_name,
                file_path,
                commit_hash[:8] if commit_hash else "none",
            )
            return result

        except Exception as e:
            logger.error("[Deployer] Deployment failed: %s", e)
            return DeploymentResult(success=False, error=str(e))

    def _write_file(self, gen_result: CodeGenerationResult) -> Path:
        """生成コードをファイルに書き出す."""
        target = gen_result.target_path
        target.parent.mkdir(parents=True, exist_ok=True)

        # ヘッダーコメントを追加
        header = (
            f'"""Auto-generated by System E CodeGenerator.\n'
            f"\n"
            f"Generated: {gen_result.generated_at}\n"
            f"Source: {gen_result.generation_context.get('source', 'unknown')}\n"
            f"Description: {gen_result.description}\n"
            f"\n"
            f"WARNING: This file was auto-generated by AI.\n"
            f"Review before using in production.\n"
            f'"""\n\n'
        )

        full_code = header + gen_result.source_code + "\n"
        target.write_text(full_code, encoding="utf-8")
        logger.info("[Deployer] File written: %s", target)
        return target

    def _git_commit(
        self, file_path: Path, gen_result: CodeGenerationResult,
    ) -> Optional[str]:
        """生成ファイルをgit commitする."""
        try:
            rel_path = file_path.relative_to(self.project_root)
        except ValueError:
            rel_path = file_path

        source = gen_result.generation_context.get("source", "unknown")
        commit_msg = (
            f"[AI-generated] {gen_result.module_name}: {gen_result.description}\n"
            f"\n"
            f"Auto-generated by System E CodeGenerator\n"
            f"Source: {source}\n"
            f"Context: {json.dumps(gen_result.generation_context, ensure_ascii=False)}"
        )

        try:
            # git add
            subprocess.run(
                ["git", "add", str(rel_path)],
                cwd=str(self.project_root),
                capture_output=True,
                text=True,
                check=True,
                timeout=30,
            )

            # git commit
            subprocess.run(
                ["git", "commit", "-m", commit_msg],
                cwd=str(self.project_root),
                capture_output=True,
                text=True,
                check=True,
                timeout=30,
            )

            # コミットハッシュを取得
            hash_result = subprocess.run(
                ["git", "rev-parse", "HEAD"],
                cwd=str(self.project_root),
                capture_output=True,
                text=True,
                check=True,
                timeout=10,
            )
            commit_hash = hash_result.stdout.strip()
            logger.info("[Deployer] Git commit: %s", commit_hash[:8])
            return commit_hash

        except subprocess.CalledProcessError as e:
            logger.error("[Deployer] Git commit failed: %s", e.stderr)
            raise RuntimeError(f"Git commit failed: {e.stderr}") from e
        except subprocess.TimeoutExpired:
            logger.error("[Deployer] Git command timed out")
            raise RuntimeError("Git command timed out")

    def _git_push(self) -> None:
        """現在のブランチをpushする."""
        cmd = ["git", "push"]
        if self.branch:
            cmd.extend(["-u", "origin", self.branch])

        try:
            subprocess.run(
                cmd,
                cwd=str(self.project_root),
                capture_output=True,
                text=True,
                check=True,
                timeout=60,
            )
            logger.info("[Deployer] Git push successful")
        except subprocess.CalledProcessError as e:
            logger.error("[Deployer] Git push failed: %s", e.stderr)
            raise RuntimeError(f"Git push failed: {e.stderr}") from e

    def _save_deploy_log(
        self,
        gen_result: CodeGenerationResult,
        val_result: ValidationResult,
        deploy_result: DeploymentResult,
    ) -> None:
        """デプロイログを保存."""
        timestamp = datetime.now(JST).strftime("%Y%m%d_%H%M%S")
        log_entry = {
            "timestamp": timestamp,
            "generation": gen_result.to_dict(),
            "validation": val_result.to_dict(),
            "deployment": deploy_result.to_dict(),
        }

        log_path = DEPLOY_LOG_DIR / f"deploy_{timestamp}.json"
        log_path.write_text(
            json.dumps(log_entry, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
        logger.info("[Deployer] Deploy log saved: %s", log_path)
